const int circuitInput;
void setup() {
  // put your setup code here, to run once:
  pinMode(2, OUTPUT);
  digitalWrite(2, LOW);
  pinMode(3, OUTPUT);
  digitalWrite(3, LOW);
  pinMode(4, OUTPUT);
  digitalWrite(4, LOW);
  pinMode(5, OUTPUT);
  digitalWrite(5, LOW);
  pinMode(6, OUTPUT);
  digitalWrite(6, LOW);
  pinMode(7, OUTPUT);
  digitalWrite(7, LOW);
  pinMode(8, OUTPUT);
  digitalWrite(8, LOW);
  pinMode(9, OUTPUT);
  digitalWrite(9, LOW);
  pinMode(10, OUTPUT);
  digitalWrite(10, LOW);
  pinMode(11, OUTPUT);
  digitalWrite(11, LOW);
  pinMode(12, OUTPUT);
  digitalWrite(12, LOW);
  pinMode(13, OUTPUT);
  digitalWrite(13, LOW);  
  pinMode(40, OUTPUT);
  digitalWrite(40, LOW);
  pinMode(41, OUTPUT);
  digitalWrite(41, LOW);  
  pinMode(42, OUTPUT);
  digitalWrite(42, LOW);
  pinMode(43, OUTPUT);
  digitalWrite(43, LOW);  
  pinMode(44, OUTPUT);
  digitalWrite(44, LOW); 
  pinMode(43, OUTPUT);
  digitalWrite(43, LOW); 
  pinMode(43, OUTPUT);
  digitalWrite(43, LOW); 
  pinMode(50, OUTPUT);
  digitalWrite(50, LOW); 
  pinMode(51, OUTPUT);
  digitalWrite(51, LOW); 
  pinMode(52, OUTPUT);
  digitalWrite(52, LOW); 
  }

void loop() {
  int s = 500;
  // put your main code here, to run repeatedly:
  digitalWrite(13, HIGH);
  delayMicroseconds(s);
  digitalWrite(13, LOW);
  digitalWrite(12, HIGH);
  delayMicroseconds(s);
  digitalWrite(12, LOW); 
  digitalWrite(11, HIGH);
  delayMicroseconds(s);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  delayMicroseconds(s);
  digitalWrite(10, LOW);
  digitalWrite(9, HIGH);
  delayMicroseconds(s);
  digitalWrite(9, LOW);
  digitalWrite(8, HIGH);
  delayMicroseconds(s);
  digitalWrite(8, LOW);
  digitalWrite(7, HIGH);
  delayMicroseconds(s);
  digitalWrite(7, LOW);
  digitalWrite(5, HIGH);
  delayMicroseconds(s);
  digitalWrite(5, LOW);
  digitalWrite(2, HIGH);
  delayMicroseconds(s);
  digitalWrite(2, LOW);
  digitalWrite(50, HIGH);
  delayMicroseconds(s);
  digitalWrite(50, LOW);
  digitalWrite(40, HIGH);
  delayMicroseconds(s);
  digitalWrite(40, LOW);
  digitalWrite(44, HIGH);
  delayMicroseconds(s);
  digitalWrite(44, LOW);
}
